First commit
danilproger/LabsNetwork pull request #1
Opened 2020-09-10 17:43 UTC by danilproger

2020-09-13 07:21 UTC, Aloomenon requested changes

2020-09-13 07:21 UTC, Aloomenon commented on Lab1/src/main/java/Main.java
> +		}
Почему необходимо закрывать сокеты?

2020-09-13 11:51 UTC, danilproger commented on Lab1/src/main/java/Main.java
> +		}
Потому что непонятно когда сработает сборщик мусора, и они могут быть открыты?

2020-09-15 15:57 UTC, Aloomenon commented on Lab1/src/main/java/Main.java
> +		}
Сборщик мусора тут не при чем. А вот что они могут быть открыты верно. К каким печальным последствиям это может привести?

2020-09-20 18:41 UTC, danilproger commented on Lab1/src/main/java/Main.java
> +		}
Печальные последствия - нехватка сокетов, то бишь в ОС их ограниченное количество, можно наспавнить их очень много, и тогда какая-нибудь другая программа завершится аварийно, тк сокет не откроется.
Как перебороть - закрывать сокеты, обрабатывать исключительные ситуации

2020-09-21 12:07 UTC, Aloomenon requested changes

2020-09-21 12:07 UTC, Aloomenon commented on Lab1/src/main/java/Main.java
> +		}
Отлично! Мысль верная. Вопрос следующий: когда multicast == null ?

2020-09-24 07:46 UTC, danilproger commented on Lab1/src/main/java/Main.java
> +		}
При создании, если конструктор выбросит IOException

2020-09-24 07:46 UTC, danilproger commented on Lab1/src/main/java/Main.java
> +		}
@Aloomenon

2020-09-24 16:12 UTC, Aloomenon approved these changes

2020-09-24 16:12 UTC, Aloomenon commented on Lab1/src/main/java/Main.java
> +		}
ок, пойдет. Имя и фамилию чирканите.

2020-09-24 16:42 UTC, danilproger commented on Lab1/src/main/java/Main.java
> +		}
Ваулин Данил

2020-09-24 16:45 UTC, danilproger commented on Lab1/src/main/java/Main.java
> +		}
@Aloomenon

2020-09-25 03:55 UTC, Aloomenon commented on Lab1/src/main/java/Main.java
> +		}
понял, принял.

2020-09-25 04:41 UTC, merged